using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class ShootManager : MonoBehaviour
{
    public Vector2 Direction;
    //’e‘¬
    [SerializeField] float _speed = 3f;
    //’eÁ¸‚Ü‚Å‚ÌŠÔ
    [SerializeField] float b_lifeTime = 5f;

    // Start is called before the first frame update
    void Start()
    {
        //’e‚ÌËo•ûŒü
        Rigidbody2D rb = GetComponent<Rigidbody2D>();
        rb.velocity = Direction * _speed;
        //ŠÔ‚ª—ˆ‚½‚çÁ¸
        Destroy(this.gameObject, b_lifeTime);
    }

    // Update is called once per frame
    void Update()
    {
        
    }

    private void OnTriggerEnter2D(Collider2D collision)
    {
        if (collision.gameObject.tag == "BOSS" || collision.gameObject.tag == "damage1")
        {
            Destroy(gameObject);
        }
    }
}
